FROM gerritforge/gerrit-ci-slave-bazel:debian-jessie AS gerrit

USER jenkins
ARG BAZEL_OPTS=""
ARG GERRIT_BRANCH="master"

RUN git clone --recursive https://gerrit.googlesource.com/gerrit /tmp/gerrit
WORKDIR /tmp/gerrit
RUN git fetch https://gerrit.googlesource.com/gerrit $GERRIT_REF && \
    git checkout FETCH_HEAD && \
    git submodule update --init
RUN bash -c \
    '. set-java.sh 8 && \
    cd /tmp/gerrit && \
    bazel build $BAZEL_OPTS gerrit'

FROM ubuntu:16.04
MAINTAINER Gerrit Code Review Community

# Include Gerrit build
COPY --from=gerrit /tmp/gerrit/bazel-bin /var/gerrit/bin

# Allow remote connectivity and sudo
RUN apt-get update
RUN apt-get -y install openssh-client sudo

# Install OpenJDK
RUN apt-get -y install openjdk-8-jdk

# Install Git
RUN apt-get -y install git

RUN adduser --disabled-password --gecos "" gerrit --home /home/gerrit
RUN chown -R gerrit /var/gerrit
USER gerrit
RUN java -jar /var/gerrit/bin/gerrit.war init --batch --install-all-plugins -d /var/gerrit
RUN java -jar /var/gerrit/bin/gerrit.war reindex -d /var/gerrit
RUN git config --add -f /var/gerrit/etc/gerrit.config container.javaOptions "-Djava.security.egd=file:/dev/./urandom"

ENV CANONICAL_WEB_URL=

# Allow incoming traffic
EXPOSE 29418 8080

VOLUME ["/var/gerrit/git", "/var/gerrit/index", "/var/gerrit/cache", "/var/gerrit/db", "/var/gerrit/etc"]

# Start Gerrit
CMD git config -f /var/gerrit/etc/gerrit.config gerrit.canonicalWebUrl "${CANONICAL_WEB_URL:-http://$HOSTNAME:8080/}" && \
    git config -f /var/gerrit/etc/gerrit.config noteDb.changes.autoMigrate true && \
        /var/gerrit/bin/gerrit.sh run
